### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Endless-ABHI** [qH0sT/AndroSpy#105]
How to install Android SDK and tool software to install all API level 17 to 29

**Comment by kulbhusha** [comment]
![Uploading Screenshot_2021-05-31-21-31-00-75.jpg…]()

**Comment by kulbhusha** [comment]
![Uploading Screenshot_2021-05-31-21-31-00-75.jpg…]()

**Comment by kulbhusha** [comment]
![Screenshot_2021-05-31-21-31-00-75](https://user-images.githubusercontent.com/70818587/120449586-2f953c00-c3ad-11eb-99fc-06935e669b0b.jpg)

**Comment by kulbhusha** [comment]
![Uploading IMG_20210602_141822.jpg…]()

**Comment by kulbhusha** [comment]
![IMG_20210602_141822](https://user-images.githubusercontent.com/70818587/120449913-7e42d600-c3ad-11eb-85cb-10f83f1510c1.jpg)

**Comment by qH0sT** [comment]
@Endless-ABHI 

![1](https://user-images.githubusercontent.com/45147475/120454855-ee952b80-c39c-11eb-9024-7fb918518882.png)

![0](https://user-images.githubusercontent.com/45147475/120454858-efc65880-c39c-11eb-9085-bf7e558bb4a9.PNG)

**Comment by Endless-ABHI** [comment]
What is this software 
Android studio"
