### ISSUE TITLE
APK file not appearing in tht/bin folder after build

### ISSUE THREAD

**Issue by Razi-Syed** [qH0sT/AndroSpy#107]
I am able to build the APK file but it is not appearing in tht/bin folder that opens after the build is complete. When I search Androspy folder with APK name I had given when building, I see folders created with that name and APK file is there. However, when I install that APK file in my Android mobiles (OS 10 and 9), it says: 'App Not Installed' 

Is there something I am not doing correctly?

**Comment by qH0sT** [comment]
check zipalign.exe path in settings.

**Comment by Razi-Syed** [comment]
Got it! There were also some Android SDKs not installed.. Thanks!
