### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by SentineL771** [qH0sT/AndroSpy#13]
hi bro
Can you contact me by mail?

**Comment by 7703034265** [comment]
Yes

**Comment by SentineL771** [comment]
@7703034265  Who are you ? are you kidding me ?

**Comment by qH0sT** [comment]
> hi bro
> Can you contact me by mail?

sen Türk değil miydin hocam? nickin sakaryalı filandı?

**Comment by jewishscientist1** [comment]
Bro I am very interested in this tool But I attempted to install it on a windows machine and I guess I couldn't quite understand How I could possibly figure it out. Any chance you could help me please ? I am completely new to this kind of things but I am very much interested in this for sure

**Comment by qH0sT** [comment]
> Bro I am very interested in this tool But I attempted to install it on a windows machine and I guess I couldn't quite understand How I could possibly figure it out. Any chance you could help me please ? I am completely new to this kind of things but I am very much interested in this for sure

Are you developer or user? if you are a developer you have to install visual studio with Xamarin KIT. Then you can modify features of program. If you are user you have to install msbuild tools, Android SDK, JAVA JRE and configure path of these in .tht file at Debug folder. I will rest for a while and then return with new edition of this program again. Maybe 6 months or 1 year later.

**Comment by jewishscientist1** [comment]
Thank you, just that I couldn't find the debug folder in the zipped file I downloaded.

**Comment by SentineL771** [comment]
> > hi bro
> > Can you contact me by mail?
> 
> sen Türk değil miydin hocam? nickin sakaryalı filandı?

Aynen dostum bir ulaşsana bana iskom@hotmail.com
