### ISSUE TITLE
Update steps the compilation

### ISSUE THREAD

**Issue by Dazmed707** [qH0sT/AndroSpy#130]
Update step for step for compile

**Comment by qH0sT** [comment]
0-)Copy AndroSpy folder to C:\
1-)Open Client project (Task2.sln) in Visual Studio
2-)Compile Client project in Visual Studio once (CTRL+SHIFT+B)
3-)Copy folders and files (except bin and obj folders) of Client Project to 'ProjectFolder' folder in 'resources' folder.
4-)Then you can build in Builder of AndroSpy.

**Comment by Dazmed707** [comment]
Done.
Thanks
