### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by rockpapersissors** [qH0sT/AndroSpy#138]
Owner of rat couldn't anwser my question.

**Comment by qH0sT** [comment]
compile the project at Visual Studio for x86?

**Comment by bazoka215** [comment]
Rebuild started...
1>------ Rebuild All started: Project: Camera, Configuration: Debug x86 ------
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(261,5): warning XA0113: Google Play requires that new applications and updates must use a TargetFrameworkVersion of v10.0 (API level 29) or above. You are currently targeting v9.0 (API level 28).
1>C:\AndroSpy-master\Client\Properties\AndroidManifest.xml : warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '22' is less than $(TargetFrameworkVersion) ''. Using API-28 for ACW compilation.
1>C:\AndroSpy-master\Client\Prev.cs(14,60,14,83): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(14,60,14,100): warning CS0618: 'Camera.IPreviewCallback' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(50,49,50,72): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(227,65,227,88): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(247,33,247,56): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(247,33,247,67): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(279,38,279,61): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(279,38,279,72): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(289,37,289,60): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(289,37,289,71): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(298,42,298,65): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(298,42,298,76): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(309,39,309,62): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(309,39,309,73): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(17,23,17,29): warning CS0108: 'Prev.Handle' hides inherited member 'Object.Handle'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(19,20,19,39): warning CS0108: 'Prev.JniIdentityHashCode' hides inherited member 'Object.JniIdentityHashCode'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(21,35,21,48): warning CS0108: 'Prev.PeerReference' hides inherited member 'Object.PeerReference'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(23,31,23,45): warning CS0108: 'Prev.JniPeerMembers' hides inherited member 'Object.JniPeerMembers'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(30,21,30,28): warning CS0108: 'Prev.Dispose()' hides inherited member 'Object.Dispose()'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(223,21,223,42): warning CS0108: 'Prev.UnregisterFromRuntime()' hides inherited member 'Object.UnregisterFromRuntime()'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\Prev.cs(16,16,16,39): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(11,23,11,29): warning CS0108: 'ImageAvailableListener.Handle' hides inherited member 'Object.Handle'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(13,20,13,39): warning CS0108: 'ImageAvailableListener.JniIdentityHashCode' hides inherited member 'Object.JniIdentityHashCode'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(15,35,15,48): warning CS0108: 'ImageAvailableListener.PeerReference' hides inherited member 'Object.PeerReference'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(17,31,17,45): warning CS0108: 'ImageAvailableListener.JniPeerMembers' hides inherited member 'Object.JniPeerMembers'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(22,21,22,28): warning CS0108: 'ImageAvailableListener.Dispose()' hides inherited member 'Object.Dispose()'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(117,21,117,42): warning CS0108: 'ImageAvailableListener.UnregisterFromRuntime()' hides inherited member 'Object.UnregisterFromRuntime()'. Use the new keyword if hiding was intended.
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(53,25,53,31): warning CS0219: The variable 'offset' is assigned but its value is never used
1>C:\AndroSpy-master\Client\LogVerileri.cs(86,24,86,36): warning CS0618: 'CursorLoader' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\LogVerileri.cs(86,52,86,64): warning CS0618: 'CursorLoader' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\LogVerileri.cs(164,24,164,36): warning CS0618: 'CursorLoader' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\LogVerileri.cs(164,52,164,64): warning CS0618: 'CursorLoader' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\SMSBroadcastReceiver.cs(34,43,34,87): warning CS0618: 'SmsMessage.CreateFromPdu(byte[]?)' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\MainActivity.cs(42,21,42,69): warning CS0618: 'Settings.System.WifiSleepPolicy' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\Prev.cs(104,29,104,52): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(129,17,129,40): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(129,17,129,51): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(231,17,231,40): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(231,17,231,51): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(232,17,232,40): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(232,17,232,45): warning CS0618: 'Camera.Size' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(252,50,252,73): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(252,50,252,84): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(254,37,254,60): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(254,37,254,71): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(258,54,258,77): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(258,54,258,88): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(260,41,260,64): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(260,41,260,75): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(264,58,264,81): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(264,58,264,92): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(266,45,266,68): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(266,45,266,79): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(270,62,270,85): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(270,62,270,96): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(272,49,272,72): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(272,49,272,83): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(284,46,284,69): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(284,46,284,80): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(286,43,286,66): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(286,43,286,77): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(293,46,293,69): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(293,46,293,80): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(295,43,295,66): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(295,43,295,77): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(303,48,303,71): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(303,48,303,82): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(305,46,305,69): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(305,46,305,80): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(314,46,314,69): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(314,46,314,80): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(316,43,316,66): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\Prev.cs(316,43,316,77): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(161,32,161,62): warning CS0618: 'Notification.Builder.Builder(Context?)' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(908,27,908,50): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(916,21,916,44): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(916,21,916,55): warning CS0618: 'Camera.CameraInfo' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(916,73,916,96): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(916,73,916,107): warning CS0618: 'Camera.CameraInfo' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(917,21,917,44): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(918,21,918,44): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(918,54,918,77): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(919,21,919,44): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(919,21,919,55): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1567,40,1567,52): warning CS0618: 'Build.Serial' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1609,30,1609,84): warning CS0618: 'TelephonyManager.DeviceId' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1771,33,1771,56): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1771,33,1771,67): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1777,74,1777,97): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1777,74,1777,108): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1780,61,1780,84): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1780,61,1780,95): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1785,74,1785,97): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1785,74,1785,108): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1788,61,1788,84): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1788,61,1788,95): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1806,33,1806,56): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1806,33,1806,67): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1812,67,1812,90): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1812,67,1812,101): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1814,60,1814,83): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1814,60,1814,94): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1816,72,1816,95): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1816,72,1816,106): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1818,60,1818,83): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1818,60,1818,94): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1823,67,1823,90): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1823,67,1823,101): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1825,60,1825,83): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1825,60,1825,94): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1843,33,1843,56): warning CS0618: 'Camera' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(1843,33,1843,67): warning CS0618: 'Camera.Parameters' is obsolete: 'This class is obsoleted in this android platform'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2062,37,2062,111): warning CS0618: 'Vibrator.Vibrate(long)' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2354,49,2354,110): warning CS0618: 'ConnectivityManager.GetNetworkInfo(ConnectivityType)' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2462,30,2462,88): warning CS0618: 'ConnectivityManager.GetNetworkInfo(ConnectivityType)' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2462,30,2462,99): warning CS0618: 'NetworkInfo.GetState()' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2511,38,2511,74): warning CS0618: 'KeyguardManager.InKeyguardRestrictedInputMode()' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2515,66,2515,89): warning CS0618: 'PowerManager.IsScreenOn' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\ForegroundService.cs(2601,17,2601,36): warning CS0618: 'BitmapFactory.Options.InPurgeable' is obsolete: 'deprecated'
1>C:\AndroSpy-master\Client\Prev.cs(19,20,19,39): warning CS0649: Field 'Prev.JniIdentityHashCode' is never assigned to, and will always have its default value 0
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(15,35,15,48): warning CS0649: Field 'ImageAvailableListener.PeerReference' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\Prev.cs(17,23,17,29): warning CS0649: Field 'Prev.Handle' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(13,20,13,39): warning CS0649: Field 'ImageAvailableListener.JniIdentityHashCode' is never assigned to, and will always have its default value 0
1>C:\AndroSpy-master\Client\Prev.cs(21,35,21,48): warning CS0649: Field 'Prev.PeerReference' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(11,23,11,29): warning CS0649: Field 'ImageAvailableListener.Handle' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\Prev.cs(23,31,23,45): warning CS0649: Field 'Prev.JniPeerMembers' is never assigned to, and will always have its default value null
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(19,37,19,56): warning CS0649: Field 'ImageAvailableListener.JniManagedPeerState' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\Prev.cs(25,37,25,56): warning CS0649: Field 'Prev.JniManagedPeerState' is never assigned to, and will always have its default value
1>C:\AndroSpy-master\Client\ImageAvailableListener.cs(17,31,17,45): warning CS0649: Field 'ImageAvailableListener.JniPeerMembers' is never assigned to, and will always have its default value null
1>  Camera -> C:\AndroSpy-master\Client\bin\x86\Debug\ServicesDemo3.dll
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(396,5): warning XA0125: 'ServicesDemo3.pdb' is using a deprecated debug information level.
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(396,5): warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the project file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug information level.
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(396,5): warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000: Unhandled exception: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at System.Diagnostics.Process.Start()
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at Xamarin.Android.Tasks.CompileNativeAssembly.RunAssembler(Config config)
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at Microsoft.Android.Build.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_1`1.<WhenAll>b__0() in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AsyncTaskExtensions.cs:line 21
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by bazoka215** [comment]
Build started...
1>------ Build started: Project: Camera, Configuration: Debug x86 ------
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(261,5): warning XA0113: Google Play requires that new applications and updates must use a TargetFrameworkVersion of v10.0 (API level 29) or above. You are currently targeting v9.0 (API level 28).
1>C:\AndroSpy-master\Client\Properties\AndroidManifest.xml : warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '22' is less than $(TargetFrameworkVersion) ''. Using API-28 for ACW compilation.
1>  Camera -> C:\AndroSpy-master\Client\bin\x86\Debug\ServicesDemo3.dll
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000: Unhandled exception: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at System.Diagnostics.Process.Start()
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at Xamarin.Android.Tasks.CompileNativeAssembly.RunAssembler(Config config)
1>C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1884,3): error XA0000:    at Microsoft.Android.Build.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_1`1.<WhenAll>b__0() in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AsyncTaskExtensions.cs:line 21
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by bazoka215** [comment]
I tried compile it in x86 dude, it won't compile succesfully, there no way you coded it to support x86. it's working fine on my x64
