### ISSUE TITLE
App works great !! but how to hide app from main menu ?

### ISSUE THREAD

**Issue by LaioX** [qH0sT/AndroSpy#139]
hi thanks for this amazing app, the problem problem i see is that the app shows in the desktop, is there any way to hide it ? because i cant hide from menu it only allows me to delete it. thanks ! (google translate)

**Comment by qH0sT** [comment]
is your Android version 10 or higer?

**Comment by LaioX** [comment]
Android 10..
I read about the new api...

Is it possible to take screenshots without getting the warning message and the red logo next to the battery?
