### ISSUE TITLE
sending wallpaper every time client connects is unnecessary as it takes extra data or might create connection issues

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#141]

**Comment by qH0sT** [comment]
wallpaper data maybe max 500 KB. There is no big data. Max max maxx 1 MB...

and I guaranteed errors/bugs, There will be no problem:

![ssss](https://user-images.githubusercontent.com/45147475/128918129-319771ab-3acd-4e07-8263-a627b8fbe394.PNG)

![aaa](https://user-images.githubusercontent.com/45147475/128918136-31d4d4a9-91eb-4fb4-a53f-9ae3b0ee5b4e.PNG)
