### ISSUE TITLE
xdd

### ISSUE THREAD

**Issue by carterjwasd** [qH0sT/AndroSpy#148]
maybe you compile client for github users fucking IDIOT

**Comment by bazoka215** [comment]
I tried compiled it on my x86 and he says compile it in Visual Studio ,I did it and I keep getting errors compiling it. lmao

**Comment by carterjwasd** [comment]
I know how to compile but many do not know
the author please compile for beginners

**Comment by qH0sT** [comment]
what the fuck, if I compile Client (generate an .apk), I must put IP or DNS and Port number. But these are option of Users. Users must determine these. @carterjwasd
