### ISSUE TITLE
APK olusturma Hatasi

### ISSUE THREAD

**Issue by zmr79** [qH0sT/AndroSpy#17]
Merhaba bende de

Message=Could not find a part of the path 'C:\Users\SADDAM\Desktop\AndroSpy-master\Server\SV\bin\Debug\outs\20200809054215/tht/bin/Google_Hesap_Servisi.apk'.

hatasi var. Apk olusturamiyor. Bu yuzden bu hatayi veriyor. Sorunu cozemedim.

settings.tht dosyasi duzgun.

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\zipalign.exe
C:\Program Files (x86)\Java\jdk1.8.0_261\bin\jarsigner.exe
C:\Users\Z\Desktop\AndroSpy-master\Server\SV\bin\Debug\sound.wav

xamarin kurulu. Client i calistirdigimda hata vermiyor fakat telefonada yukleme yapmiyor. Yardimci olursaniz cok sevinirim.

**Comment by kagami01** [comment]
Merhaba kardesim!
discord var mi?hic zor degil ama size yardim yapabilir su anda

**Comment by zmr79** [comment]
discord ali.ali tesekkurler.

**Comment by kagami01** [comment]
gunaydin
tmm)

**Comment by zmr79** [comment]
ok tesekkur ederim bekliyorum.

**Comment by zmr79** [comment]
Merhaba kardeşim, Saat 15:00 dan sonra internetim olmayacak. Daha once musait olur musun?

**Comment by zmr79** [comment]
Gunaydin kardesim bugun halledermiyiz dun bekledim ama musait degildin sanirim

**Comment by kagami01** [comment]
gunaydin)tamam merak etemyin.discord da bekilyorum. eklemek sona orada takalim
iyi gunler

ps
tut chat degil))

> discord ali.ali tesekkurler.

ali.ali sadece  yeter degil..tag siz bulamadim size...tag li gerek lazim

**Comment by zmr79** [comment]
ali.ali#5550

**Comment by qH0sT** [comment]
Hocam mayıs ayında başlayacağım projeyi devam ettirmeye, o sırada da problemleri çözmeye çalışıcam.
