### ISSUE TITLE
System.IO.DirectoryNotFoundException : Could not find a part of the path

### ISSUE THREAD

**Issue by BotterModder** [qH0sT/AndroSpy#183]
I keep getting this error when i want to build, I really don't know what messed out, I compiled both, Client and Server, checked sdk platforms, 
![image](https://user-images.githubusercontent.com/95588026/144760715-07cf17ce-ddea-426a-b8b0-357e43438b61.png)

**Comment by BotterModder** [comment]
Resolved

**Comment by runrungogo** [comment]
Excuse me how to solve
