### ISSUE TITLE
Random users connect to server

### ISSUE THREAD

**Issue by freakerparty** [qH0sT/AndroSpy#27]
Hello,

I have a firewall that can detect single connections. And sometimes I get random people from different countries that try to connect and some are even in my list and I see a storm of SMS sent to that person, when i click on that person my program crashes. Maybe it's a good idea to add a client password that has to be the same as the server. So random people can't connect and the security is on both sides better because of a password protection :)

That extra layer feels more secure.

**Comment by qH0sT** [comment]
> Hello,
> 
> I have a firewall that can detect single connections. And sometimes I get random people from different countries that try to connect and some are even in my list and I see a storm of SMS sent to that person, when i click on that person my program crashes. Maybe it's a good idea to add a client password that has to be the same as the server. So random people can't connect and the security is on both sides better because of a password protection :)
> 
> That extra layer feels more secure.

Yes good idea password but how that happens? You create a client with your own IP address and Port, and you need to run this client on different devices so that clients come from different locations. Did you scan your client in places like VirusTotal?

**Comment by freakerparty** [comment]
Hmmm, this sucks, yes i uploaded the client to virustotal, i didn't knew my IP was going to be in there. Any advise on what i should do?

**Comment by freakerparty** [comment]
@qH0sT I openend a support ticket to remove the scan, since my IP adres is in it people are constantly trying to connect to my device. If i didn't had a Firewall installed per connection I wouldn't even see all the connections trying to connect to my device. It's still strange, I've seen mobiles from Russia connect, and I can see their mobile brand, their IP and mostly it's flooding sms messages. But as soon as i click on one of the users the app crashes. For now I've set my firewall to max and only allow connections manually. I hope Virustotal will follow my request and delete my IP.

**Comment by freakerparty** [comment]
My IP has been removed and the password setting has reaolved the security issue :)
