### ISSUE TITLE
JSON IMPLEMENTATION

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#48]
Please use data as JSON while sending request and response between server and client, so that it'll be easy for others to code their own server panel.

in my case, I want to code web-based server panel using nodejs but I couldn't understand the data syntax properly.

**Comment by qH0sT** [comment]
> Please use data as JSON while sending request and response between server and client, so that it'll be easy for others to code their own server panel.
> 
> in my case, I want to code web-based server panel using nodejs but I couldn't understand the data syntax properly.

Now I will release new update, it is ready. In this new version I am sending data with byte array (byte[]) and with it's tag (string) you can easyly handle for read data with UnPacker class in this new update, convert it to JavaScript or PHP; your language.

![byte](https://user-images.githubusercontent.com/45147475/105629381-b95b5880-5e53-11eb-9756-657c51c02673.PNG)
