### ISSUE TITLE
Rat for windows ?

### ISSUE THREAD

**Issue by Dazmed707** [qH0sT/AndroSpy#50]
have you thought about launching a mouse created by you for windows?

can be based on one of these projects

https://github.com/quasar/Quasar
https://github.com/NYAN-x-CAT/AsyncRAT-C-Sharp

**Comment by qH0sT** [comment]
I am currently focusing to Android RAT, I don't think make a windows RAT.  Did you mean that?

**Comment by Dazmed707** [comment]
Ah good ..
esta bien
but I still haven't been able to use the android mouse, I get an error when compiling the client
