### ISSUE TITLE
A great project. Thanks for open source and your efforts.

### ISSUE THREAD

**Issue by johanlike** [qH0sT/AndroSpy#56]
A great project. Although this program has some minor bugs, it has surpassed many other Android spy programs. :thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup:

**Comment by qH0sT** [comment]
Thanks, now I have fixed microphone bug, don't use until I update new .cs file, now I am uploading new .cs files.

**Comment by qH0sT** [comment]
I have updated .cs files, now you can use it :)

**Comment by johanlike** [comment]
> I have updated .cs files of Client, now you can use it :)

Thanks you!
