### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by s1l3nt78** [qH0sT/AndroSpy#57]
Hey not sure if im just not looking in the right place.
But I dont see a builder option on the new build
![Screenshot 2021-02-17 145410](https://user-images.githubusercontent.com/44367179/108207190-133bff00-7130-11eb-9173-df73512f675e.png)

**Comment by shangow** [comment]
Hey, the builder is located on the right card of the windows, where the notifications are click on the right mouse button above the androspy icon

**Comment by shangow** [comment]
https://github.com/qH0sT/AndroSpy/issues/55#issuecomment-780250467

**Comment by s1l3nt78** [comment]
Thanks will try now, I have used this before so building it isnt a problem just couldnt find the builder.
Thanks for the quick reply though 👌
