### ISSUE TITLE
NEED QUICK HELP - REGARDING STRING UPACKING

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#71]
HOW TO UNPACK OR DECRYPT OR DECODE THIS STRING IN NODEJS OR PYTHON??

<MYIP>|476365|null>[VERI]Victim[VERI]GB/en[VERI]samsung/SM-N975F[VERI]11.0/30[VERI]iVBORw0KGgoAAAANSUhEUgAABZ8AAAx5CAIAAAAek6IeAAAAAXNSR0IArs4c6QAAAANzQklUCAgI2+FP4AAAIABJREFUeJzs3duT5Od5H/bneX+/7pnZ2SOwWJxBkDQlkJZkSZRiW5Fom6q4KpVSJReJb1xSqlzlW/u/8IV97wvfqFyKXUnomyi2q5JKRbFkx2YsiTqUJFoiRYLEGVgAe5hTd//eJxc9M7vYBUiaJGZ2dz6fGgx6+rTv1GAK299+DhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGdNO+0DAAAAAJyoPO0DAAAAANzr/vKNlGLcbzjtAwAAAAAfqmVkRN11TUa0o4Dj8KbMe8KO9X0qI1tEZmRGRtZ9z5GPUEoi3QAAAIAHU30w2vjQO3wHraLyrsuHmchx8cd3fvRD5RHJaTJzGIaqmqbptM8CAAAAH4f8joHEcTXHcXSR69KNOPo6IiJ6RH/00o1Hp3ajqnrvp30KAAAA+OH4jp0j+cHLxx0r3+Fuxx6hVOPIo5ButNZaO5yzMgyPwncEAAAAHxFYRB7N0rhzRYyReVdxx/F7/3X0kXddfgQ9CllAHVlfPu3jAAAAwA/FkHcFHB8s5ajjr/KoAyXX19+JNjKOHpyZkXX/ApZHZv/KQ59uzGazzNzY2Nje3p7NZut0o7Um5gAAAOAhlxH9rlEaee+NERHrXoaed+oy1l0qQ0Q7+qiI+6ON9V6VR8R42gf4Qc3n80984hMvvfTSJz7xicVi8Sd/8id/+qd/+sYbb5z2uQAAAOAHdFyFcVzBsbpzY62vrMO2k4yqw/tnDOtCj3XaUdEipuiHu2PrTnNKq3hE5lc+TDFNa209N3QYht77bDabz+df+MIX/vbf/ts/8RM/ce3ateVy+fLLL//mb/7mP/tn/+yrX/3qarU6fsj6UTaqAAAA8DBpET3XjRcZU0WtSzWqImKoWjdk9OPUI4eIiuqxHsaRmT0iqyp6xPTB542jx3KCMnMdMh3b2Nj4whe+8Bu/8Rs3btxYLBa992maDg4OXnnllX/8j//xiy++eM8zGDgKAADAQ6ZFtIxo2cYc2uFsjYwcYpzN27ARMUaOkUNERovZ5jDfGnLIyBjH2cbG1tBmR/0pdz/pcN+VnIjjaGO9HmUYhkuXLv2Df/APbt682Xtfr4NdW61Wf/RHf/TLv/zLp3peAAAA+AG1zCHz6K36w60oLY9SicxoGRHR2jCM8zbMo

Thanks in advance.

**Comment by 1337C0D3RS** [comment]
in the previous version, I was able to read string contents but now looks like it's compressed or encoded, so need help.

**Comment by qH0sT** [comment]
this is base64 encoded image of your phone's Wallpaper.

**Comment by AngelBlaizeC** [comment]
Regarding this.. i am also working on a different Server using nodeJS.. i was wondering about the livecam. <VID> packet im sure the feed is in jpeg format. but when I write it in a file its not a valid jpeg image. i make sure i removed the <EOF>SUFFIX and instruction packet at the first. is the jpeg encoded?  or do i need to use an unpacker or something? hope you understand my point

**Comment by qH0sT** [comment]
> Regarding this.. i am also working on a different Server using nodeJS.. i was wondering about the livecam. [VID] packet im sure the feed is in jpeg format. but when I write it in a file its not a valid jpeg image. i make sure i removed the [EOF]SUFFIX and instruction packet at the first. is the jpeg encoded? or do i need to use an unpacker or something? hope you understand my point

string data = "<MYTAG|lenght of data|null>";

     byte [ ] data that fully received
---------------------------------------------
(bytes) <MYTAG|lenght of data|null> (remove this with byte remover)
(bytes) Main Data like image or etc.
(bytes) <EOF> (remove this with byte remover)
(bytes) SUFFIX (remove this with byte remover)
-----------------------------------------------

The main data you finally got after remove tag, eof, suffix bytes;

------------------------------------
(bytes) Main Data like image or etc.
------------------------------------

byte [ ] lastData = (bytes) Main Data;

process data like;  File.WriteAllBytes("myimage.jpg", lastData);

I hope this will help you :)

**Comment by AngelBlaizeC** [comment]
Yes it worked. Thanks a lot :)
