### ISSUE TITLE
I can't re-install client

### ISSUE THREAD

**Issue by 9173H4vvK** [qH0sT/AndroSpy#83]
Hello, 
I have tried on different models, whenever application is installed at launching time it gives you connection as after installation of apk installer gives option to open the installed application.

But if you resinstall the application i wont give any option to launch the application. As in most of the devices it has no icon. is there any option to bind it with other apk. or 
any solution will be much appreciated.

**Comment by qH0sT** [comment]
before install new apk, you must uninstall old apk.

**Comment by 9173H4vvK** [comment]
Hey thanks for quick response, 
i have tried on Oppo and Chinese brand phone, this issue actually exists. It has to be same as you replied but it can be reinstalled. Here are some of screenshots.
Main issue is after reinstall it doesnt give option to open the app again as no icon there.
here it is the 1st time install.
![Screenshot_2021-04-22-12-53-36-64](https://user-images.githubusercontent.com/79447399/115680442-69801680-a308-11eb-8728-2f358ee980d6.jpg)
here is 2nd time installation screenshots.
![Screenshot_2021-04-22-13-00-17-78](https://user-images.githubusercontent.com/79447399/115680740-b19f3900-a308-11eb-9e33-3d4acfec5684.jpg)
![Screenshot_2021-04-22-13-00-27-75](https://user-images.githubusercontent.com/79447399/115680753-b49a2980-a308-11eb-929d-2f06d98ecab1.jpg)

as you can see no one can open it again, also restarting the phone wont restart the activity too.  Please address

**Comment by qH0sT** [comment]
could you see the old app in Installed Application menu of phone? if you see, uninstall it then retry.

**Comment by 9173H4vvK** [comment]
Yes i can see that and uninstall that too, but my point is why it can be installed again on existing installed apk, and is there any way to bind with something, please help

**Comment by qH0sT** [comment]
> Yes i can see that and uninstall that too, but my point is why it can be installed again on existing installed apk, and is there any way to bind with something, please help

Delete old apk file from Files of Phone. And I don't know how we can bind with another apk. Already the size of client is nearly 14-15MB. Apk bind would not be good because of that.

**Comment by Kevin2021-jk** [comment]
Every time a new version is released, I am very serious to test it, there is always a problem, the first time you install the apk on Android, and then open the main AndroSpy.exe, very normal online, when you turn off the main AndroSpy.exe, open it again will be permanently offline. Can only restart the Android device again to reconnect, if you can do every time you open the main AndroSpy.exe, will actively go to connect to the Android device is the best. Thanks to the author!

**Comment by qH0sT** [comment]
> Every time a new version is released, I am very serious to test it, there is always a problem, the first time you install the apk on Android, and then open the main AndroSpy.exe, very normal online, when you turn off the main AndroSpy.exe, open it again will be permanently offline. Can only restart the Android device again to reconnect, if you can do every time you open the main AndroSpy.exe, will actively go to connect to the Android device is the best. Thanks to the author!

wtf! this is a software and I must release update if I see a bug or else, what's weird about that?? I try to make it better. I check errors-bugs at my free times. I don't give my whole time for this! I can't do more for chinese brand phones! thanks.
