### ISSUE TITLE
NOT WORKING WHEN DEVICE IS LOCKED IN XIAOMI DEVICES

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#86]

**Comment by 1337C0D3RS** [comment]
most of the time when the device is locked it won't show up and sometimes when internet is kinda slow it won't work at all...


Please look into it and thank in advance.

**Comment by qH0sT** [comment]
https://dontkillmyapp.com/xiaomi

**Comment by 1337C0D3RS** [comment]
thanks lemme check and revert back
