### ISSUE TITLE
Does not work when screen is in lock mode?

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#87]
Not working when device is in lock mode :(

i have used spynote.us once and it was working perfectly then... can you please try to find the source and implement the same?

Thanks in advance & kudos to your commitment.

**Comment by 1337C0D3RS** [comment]
i tried your suggestion of trying everything mentioned on
https://dontkillmyapp.com/xiaomi but still when the device is locked state its not working in xiaomi devices...

while whatsapp works perfectly... what could be the reason?

**Comment by qH0sT** [comment]
@1337C0D3RS

1-)SpyNote uses CPU Wakelock, this may work fine, but will consume a lot of your battery. I can  do this but this causes battery drain.

2-)WhatsApp and other messaging apps (Telegram or etc.) uses Google Firebase. Firebase is exception from sleeping mode on all android devices.

You can add CPU Wakelock into the source code: (Go to ``ForeGroundService.cs`` then put this below codes into ``public override void OnCreate()`` method.)

CPU Wakelock codes:

``PowerManager pmanager = (PowerManager)this.GetSystemService("power");
wakelock = pmanager.NewWakeLock(WakeLockFlags.Partial, "cpu-wakelock");
wakelock.SetReferenceCounted(false);
wakelock.Acquire();``

then it works fine in lock mode or screen close on your Xiaomi device.

**Comment by 1337C0D3RS** [comment]
Thanks alot i'll try this

**Comment by 1337C0D3RS** [comment]
@qH0sT and also may be you can give checkbox on apk builder in future release so that people can opt whether theywant to enable cpu wakelock or not...

it'll be easier for others who don't know coding but want to enable cpu wakelock :)

**Comment by 1337C0D3RS** [comment]
> @1337C0D3RS
> 
> 1-)SpyNote uses CPU Wakelock, this may work fine, but will consume a lot of your battery. I can do this but this causes battery drain.
> 
> 2-)WhatsApp and other messaging apps (Telegram or etc.) uses Google Firebase. Firebase is exception from sleeping mode on all android devices.
> 
> You can add CPU Wakelock into the source code: (Go to `ForeGroundService.cs` then put this below codes into `public override void OnCreate()` method.)
> 
> CPU Wakelock codes:
> 
> `PowerManager pmanager = (PowerManager)this.GetSystemService("power"); wakelock = pmanager.NewWakeLock(WakeLockFlags.Partial, "cpu-wakelock"); wakelock.SetReferenceCounted(false); wakelock.Acquire();`
> 
> then it works fine in lock mode or screen close on your Xiaomi device.

app is crashing after adding this line... i also declared wakelock still its crashing

**Comment by 1337C0D3RS** [comment]
@qH0sT i badly need it please help, thanks in advance!

**Comment by qH0sT** [comment]
add this code into ``try{ }catch(Exception ex) { Debug.WriteLine(ex.Message); }`` block and check what error is with Visual Studio.

I will add cpu wakelock into Builder with checkBox option in next release (after 1 month) (I'm working on RAT for code optimisation, stability and memory usage etc. and some UI changes).

**Comment by 1337C0D3RS** [comment]
> add this code into `try{ }catch(Exception ex) { Debug.WriteLine(ex.Message); }` block and check what error is with Visual Studio.
> 
> I will add cpu wakelock into Builder with checkBox option in next release (after 1 month) (I'm working on RAT for code optimisation, stability and memory usage etc. and some UI changes).

awesome... thanks for the reply!

**Comment by 1337C0D3RS** [comment]
even after adding cpu wake lock its not working in lock screen mode any other solution?
