### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#88]
If possible, pleaseeee give us an option to restart and switch off device remotely.

Thanks in advance.

**Comment by qH0sT** [comment]
I will think this.

**Comment by Kevin2021-jk** [comment]
The biggest problem in the test now is that after the main control is closed, it will not be connected when it is turned on again. When the main control is running again, the APP that actively connects to the device is perfect and powerful.
