### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 1337C0D3RS** [qH0sT/AndroSpy#89]
Is there any way that mobile data can be turned on just by sending a secret code as sms to victim's mobile number?

If yes, that could help alot!

Work Flow:

1. User sends a secret message to victim mobile. 
2. Every time new message arrives, android app checks if
it contains that secret code using regex.
3. If it contains a unique secret code then android app will turn on mobile data and deletes the message received.

**Comment by 1337C0D3RS** [comment]
@qH0sT

**Comment by qH0sT** [comment]
Really good idea.
you are a programmer?
In my opinion also you can make this.  Just few search on google ;)
I'm tried because of this program, actually I don't want to add another feature, only a updates/fixes is enough for me :)
