### ISSUE TITLE
live screen can't work on Mi 9 Android 11

### ISSUE THREAD

**Issue by PaperPlaneDeemo** [qH0sT/AndroSpy#94]
i have already turn on the accessible service but it didn't work

**Comment by qH0sT** [comment]
@PaperPlaneDeemo 

Not accessible service,

2-)For live screen you must accept dialog that is shown when start button is pressed. Like this Image =>

![117148878-5452bf80-adbf-11eb-944d-99baa0e7bb40](https://user-images.githubusercontent.com/45147475/117573375-254e8d80-b0e0-11eb-8497-d9a7b8522780.jpg)

**Comment by qH0sT** [comment]
![ls](https://user-images.githubusercontent.com/45147475/117573424-68a8fc00-b0e0-11eb-8d14-455eab0f7b0d.PNG)

**Comment by PaperPlaneDeemo** [comment]
sorry, but there's no such a dialog shown after i press the start buttom

**Comment by qH0sT** [comment]
> sorry, but there's no such a dialog shown after i press the start buttom

check for permissions in Settings of Device, because something similar had happened to another user, like your situation.

**Comment by andrescastro7036** [comment]
hi, any way to bypass that screen sharing dialog?
