### ISSUE TITLE
Please Help 

### ISSUE THREAD

**Issue by bechirchebbah1** [qH0sT/AndroSpy#95]
![image](https://user-images.githubusercontent.com/69391858/118348134-762f0d80-b548-11eb-80b7-630af4f4ec51.png)
can't compile when xamarin already installed and i'am using visual studio 2019

**Comment by qH0sT** [comment]
@bechirchebbah1 

install android sdk api level 28:

![0](https://user-images.githubusercontent.com/45147475/118353711-39770c80-b570-11eb-90d7-c9ea5db2f3c7.PNG)

**Comment by bechirchebbah1** [comment]
@qH0sT i will try now thanks for reply

**Comment by bechirchebbah1** [comment]
i followed your video https://www.youtube.com/watch?v=MbZJDwBrvDE and still getting this error
![image](https://user-images.githubusercontent.com/69391858/118354183-177a8b80-b56a-11eb-861d-0d5e5d68ea31.png)

**Comment by bechirchebbah1** [comment]
@qH0sT please help me
